In [1]:
import pandas as pd
import numpy as np
import os 
import scipy.stats as stats

In [2]:
crash_data_LA = os.path.join(os.getcwd(), "data", "Crash_Data_LA_COUNTY.csv")
harsh_accleration_LA = os.path.join(os.getcwd(), "data", "Harsh_Acceleration_LA_COUNTY.csv")
harsh_braking_LA = os.path.join(os.getcwd(), "data", "Harsh_Braking_LA_COUNTY.csv")
poi_LA = os.path.join(os.getcwd(), "data", "POI_LA_COUNTY.csv")
df_crashData = pd.read_csv(crash_data_LA)
df_harshAccelerationData = pd.read_csv(harsh_accleration_LA)
df_harshBrakingData = pd.read_csv(harsh_braking_LA)
df_POIData = pd.read_csv(poi_LA)
df_crashData.head()

,LATITUDE,LONGITUDE,ARC_ID,YEAR,VH,CYC,PED,FATAL,SERIOUS_INJURY,MINOR_INJURY,NO_INJURY
0,34.022659,-118.438652,3815613985340226038495917846_38156133053402269...,2018.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,33.771053,-118.240303,3817593925337726257993907375_38175966053377030...,2018.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,34.025581,-118.335114,38166473753402558910272263152_3816648955340255...,2018.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,34.164879,-118.410530,3815895015341648791916620220_38158843353416488...,2019.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,33.969830,-118.347229,3816528095339698383331497996_38165261453396974...,2019.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [3]:
corr_matrix = round(df_crashData.corr(),5)
corr_matrix

,LATITUDE,LONGITUDE,ARC_ID,YEAR,VH,CYC,PED,FATAL,SERIOUS_INJURY,MINOR_INJURY,NO_INJURY
LATITUDE,1.00000,-0.12690,-0.00836,0.00196,0.08176,-0.05592,-0.05563,0.02708,0.01047,0.00024,-0.01303
LONGITUDE,-0.12690,1.00000,-0.02636,0.11934,0.03178,-0.00425,-0.03508,-0.00007,-0.02717,0.01148,0.00400
ARC_ID,-0.00836,-0.02636,1.00000,-0.01061,-0.00914,0.00082,0.01040,0.00819,-0.00148,-0.00340,0.00188
YEAR,0.00196,0.11934,-0.01061,1.00000,0.05444,-0.04199,-0.03339,0.01755,0.05593,0.02709,-0.06076
VH,0.08176,0.03178,-0.00914,0.05444,1.00000,-0.56441,-0.77243,-0.10031,-0.13792,-0.08664,0.18351
CYC,-0.05592,-0.00425,0.00082,-0.04199,-0.56441,1.00000,-0.08830,-0.00555,0.01986,0.08632,-0.09103
PED,-0.05563,-0.03508,0.01040,-0.03339,-0.77243,-0.08830,1.00000,0.12531,0.15115,0.03813,-0.15140
FATAL,0.02708,-0.00007,0.00819,0.01755,-0.10031,-0.00555,0.12531,1.00000,-0.03825,-0.08947,-0.15612
SERIOUS_INJURY,0.01047,-0.02717,-0.00148,0.05593,-0.13792,0.01986,0.15115,-0.03825,1.00000,-0.19929,-0.34774
MINOR_INJURY,0.00024,0.01148,-0.00340,0.02709,-0.08664,0.08632,0.03813,-0.08947,-0.19929,1.00000,-0.81341
NO_INJURY,-0.01303,0.00400,0.00188,-0.06076,0.18351,-0.09103,-0.15140,-0.15612,-0.34774,-0.81341,1.00000

In [4]:
nan_count_crashData = np.sum(df_crashData.isnull(), axis = 0)
nan_detected_crashData = nan_count_crashData != 0 
print(nan_detected_crashData)

LATITUDE          False
LONGITUDE         False
ARC_ID            False
YEAR               True
VH                 True
CYC                True
PED                True
FATAL              True
SERIOUS_INJURY     True
MINOR_INJURY       True
NO_INJURY          True
dtype: bool

In [5]:
df_harshAccelerationData.head()
nan_count_harshAcceleration = np.sum(df_harshAccelerationData.isnull(), axis = 0)
nan_detected_harshAcceleartion = nan_count_harshAcceleration != 0 
print(nan_detected_harshAcceleartion)

CLUSTER_ID                  False
VEHICLE_COUNT               False
CENTROID                    False
POLYGON                     False
RANK                        False
MULTILINESTRING_CLUSTERS     True
LENGTH_CLUSTER               True
LIST_ROAD_NAME              False
LIST_CITY_NAME              False
LIST_ROAD_PRIORITY          False
H3_ID                       False
H3_GEOM                     False
dtype: bool

In [6]:
df_crashData['LATITUDE'] = stats.mstats.winsorize(df_crashData['LATITUDE'], (0.1, 0.1))
print(df_crashData['LATITUDE'])

0         34.022659
1         33.864838
2         34.025581
3         34.164879
4         33.969830
            ...
290882    34.141766
290883    34.257187
290884    34.219341
290885    34.228191
290886    34.228191
Name: LATITUDE, Length: 290887, dtype: float64

In [7]:
#print(df_crashData.nlargest(10, columns = ['LATITUDE']))
print(df_crashData.nsmallest(10, columns = ['LATITUDE']))

      LATITUDE   LONGITUDE                                             ARC_ID  \
1    33.864838 -118.240303  3817593925337726257993907375_38175966053377030...
61   33.864838 -118.274170  3817258405337792517455726058_38172583253377933...
657  33.864838 -118.290222  381709351533728793627621612_381709824533728791...
658  33.864838 -118.290222  381709824533728791123165350_381709351533728793...
748  33.864838 -118.107552  3818926355337539378689267527_38189244953375413...
749  33.864838 -118.107552  3818924495337541378689267521_38189263553375393...
751  33.864838 -118.094658  381905341533857899297828019_381905330533858306...
752  33.864838 -118.182388  381817599533769253122873563_381817604533769402...
768  33.864838 -118.191208  381808900533789870123054521_381808251533789860...
769  33.864838 -118.191208  381808251533789860123161008_381808900533789870...

       YEAR   VH  CYC  PED  FATAL  SERIOUS_INJURY  MINOR_INJURY  NO_INJURY
1    2018.0  0.0  1.0  0.0    1.0             0.0           0.0        0.0
61   2020.0  1.0  0.0  0.0    0.0             0.0           0.0        1.0
657  2021.0  0.0  0.0  1.0    0.0             0.0           1.0        0.0
658  2021.0  0.0  0.0  1.0    0.0             0.0           1.0        0.0
748  2020.0  1.0  0.0  0.0    0.0             0.0           0.0        1.0
749  2020.0  1.0  0.0  0.0    0.0             0.0           0.0        1.0
751  2019.0  1.0  0.0  0.0    0.0             0.0           1.0        0.0
752  2020.0  0.0  1.0  0.0    0.0             0.0           1.0        0.0
768  2020.0  0.0  1.0  0.0    0.0             0.0           1.0        0.0
769  2020.0  0.0  1.0  0.0    0.0             0.0           1.0        0.0